config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
  root "application#index"

  resources :books
  resources :authors do
    get :search, on: :collection
    resources :books, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  accepts_nested_attributes_for :books

  validates :first_name, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 0, message: "negative age is not allowed" }
  validates :last_name, presence: true, length: { maximum: 10 }



  def name
    "#{first_name} #{last_name}"
  end
  
  def name_age
    "#{first_name} #{last_name} (#{age})"
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :book_genres
  has_many :genres, through: :book_genres

  validates :title, presence: true, uniqueness: true

  before_save :set_time_now_publish_date

  after_save :log_published_date

  def set_time_now_publish_date
    self.publish_date = Time.zone.now
  end

  def log_published_date
    puts "Book #{title} was published on #{publish_date}"
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres 
  has_many :books, through: :book_genres
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @authors = Author.all.order(:first_name, :last_name)
  end

  def show
    @author = Author.find_by(id: params[:id])
    @books = @author.books
  end

  def new
    @author = Author.new
    puts "session: #{session[:user_id]}"
  end

  def search
    string = params[:text]
    @authors = Author.where("first_name LIKE ? OR last_name LIKE ?", "%#{string}%", "%#{string}%")
    render layout: false
  end

  def create
    puts "params: #{params}"
    author = Author.new(author_params)

    respond_to do |format|
      if author.save
        format.html { redirect_to authors_path }
        format.json { render json: author.to_json }
      else
        format.html { redirect_to new_author_path }
        format.json { render json: author.errors }
      end
    end
  end

  def edit
    @author = Author.find_by(id: params[:id])
  end

  def update
    author = Author.find_by(id: params[:id])

    if author.update!(author_params)
      redirect_to authors_path
    else
      render :edit
    end
  end

  def destroy
    author = Author.find_by(id: params[:id])
    author.destroy
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :age, books_attributes: [:title, :year, :price, :publish_date])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.all.preload(:author).order(:id)
  end

  def show
    @book = Book.find_by(id: params[:id])
    @genres = @book.genres
  end

  def new
    @book = Book.new
    if params[:author_id].present?
      @book.author = Author.find_by(id: params[:author_id])
    end
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created successfully"
      redirect_to book_path(@book)
    else
      flash[:error] = "Book creation failed"
      redirect_to new_book_path
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
    @authors = Author.all
  end

  def update
    @book = Book.find_by(id: params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book update successfully"
      redirect_to book_path(@book)
    else
      flash[:error] = "Book update failed"
      redirect_to edit_book_path(@book)
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    if @book.destroy
      flash[:notice] = "Book deleted successfully"
    else
      flash[:error] = "Book deletion failed"
    end
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_id, :year, :price, :publish_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1> Index </h1>

app/views/authors/_form.html.erb
<%= form_with model: author, local: true do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control", required: true %>
  </div>
    <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control", required: true %>
  </div>
    <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, class: "form-control" %>
  </div>
  <% if author.new_record? %>
   <h2> Book </h2>
   <%= form.fields_for :books, Book.new do |book_form| %>
    <div class="form-group">
      <%= book_form.label :title %>
      <%= book_form.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= book_form.label :price %>
      <%= book_form.number_field :price, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= book_form.label :year %>
      <%= book_form.number_field :year, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= book_form.label :publish_date %>
      <%= book_form.date_field :publish_date, class: "form-control", required: true %>
    </div>
  <% end %>

  <% end %>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1> Edit Author </h1>  

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<div class="container">
  <h1 style="color:blue"><i class="bi bi-person-circle"></i> Author </h1>

  <% if user_signed_in? %>
    <%= link_to "New Author" ,new_author_path, class: "btn btn-primary mb-3" %>
  <% end %>

  <div class="input-group mb-3">
    <input id="textoBusqueda" type="text" name="search" class="form-control" placeholder="Search author by name" aria-label="Search author by name" aria-describedby="button-addon2">
    <button class="btn btn-outline-secondary" type="button" id="buscador">Search</button>
  </div>

<div id="result">
    <table class="table table-bordered align-middle">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @authors.each_with_index do |author, index| %>
        <tr>
          <th scope="row"><%= index %></th>
          <td><%= author.name %></td>
          <td><%= author.age %></td>
          <td>
            <%= link_to author, class: "btn btn-outline-primary"  do %>
              <i class="bi bi-eye"></i>
            <% end %>
            <%= link_to edit_author_path(author), class: "btn btn-outline-warning" do %>
              <i class="bi bi-pencil"></i>
            <% end %>
            <%= link_to author, data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: "btn btn-outline-danger" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  document.getElementById('buscador').addEventListener('click', function (event) {
    event.preventDefault();

    let textoBusqueda = document.getElementById('textoBusqueda').value;

    fetch('/authors/search?text=' + textoBusqueda, {
      request: 'GET', 
      headers: {
        'Content-Type': 'application/html'
      }}).then(response => {
        console.log(response);
        return response.text();
      }).then(html => {
        console.log(html);
        document.getElementById('result').innerHTML = html;
      });
  });
</script>

app/views/authors/new.html.erb
<h1> New Author </h1>

<%= render "form", author: @author %>

app/views/authors/search.html.erb
  <table class="table table-bordered align-middle">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each_with_index do |author, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= author.name %></td>
        <td><%= author.age %></td>
        <td>
          <%= link_to author, class: "btn btn-outline-primary"  do %>
            <i class="bi bi-eye"></i>
          <% end %>
          <%= link_to edit_author_path(author), class: "btn btn-outline-warning" do %>
            <i class="bi bi-pencil"></i>
          <% end %>
          <%= link_to author, data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: "btn btn-outline-danger" do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>

app/views/authors/show.html.erb
<h1> <%= @author.name%> </h1>
<p> <%= @author.age %> </p>
<p> Books: <%= @books.size %></p>

<%= link_to new_author_book_path(author_id: @author.id), class: "btn btn-success" do %>
  <i class="bi bi-plus"></i> Add book
<% end %>

<table class="table">
  <thead>
    <tr>
      <th> Title </th>
      <th> Year </th>
      <th> Price </th>
      <th> Publish date </th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td> <%= book.title %> </td>
        <td> <%= book.year %> </td>
        <td> <%= book.price %> </td>
        <td> <%= book.publish_date %> </td>
        <td>
          <%= link_to book_path(book), class: "btn btn-info" do %>
            <i class="bi bi-eye"></i>
          <% end %>
          <%= link_to edit_book_path(book), class: "btn btn-warning" do %>
            <i class="bi bi-pencil"></i>
          <% end %>
          <%= link_to book_path(book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to authors_path, class: "btn btn-primary" do%>
  <i class="bi bi-arrow-90deg-left"></i> Back
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :publish_date %>
    <%= form.date_field :publish_date, class: "form-control" %>
  </div>
  <% if book.author.present? %>
    <div class="form-group mb-3">
      <%= form.label :author %>
      <%= form.hidden_field :author_id, value: book.author_id %>
      <%= form.text_field :author, value: book.author.name, class: "form-control", disabled: true %>
    </div>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label :author_id %>
      <%= form.collection_select :author_id, @authors, :id, :name_age, {prompt: 'Please select the author of this post'}, { class: "form-select" }%>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book </h1>

<%= render "form", book: @book, authors: @authors, author: @book.author %>

app/views/books/index.html.erb
<div class="container">
  <h1 style="color:blue"><i class="bi bi-book"></i> BOOKS </h1>

  <%= link_to "New Book", new_book_path, class: "btn btn-primary mb-3" %>
  <table class="table table-bordered align-middle">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Year</th>
        <th scope="col">Price</th>
        <th scope="col">Author</th>
        <th scope="col">Publish Date</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <th scope="row"><%= book.id %></th>
        <td><%= book.title %></td>
        <td><%= book.year %></td>
        <td><%= book.price %></td>
        <td><%= book.author.name %></td>
        <td><%= book.publish_date %></td>
        <td>
          <%= link_to book, class: "btn btn-outline-primary"  do %>
            <i class="bi bi-eye"></i>
          <% end %>
          <%= link_to edit_book_path(book.id), class: "btn btn-outline-primary" do %>
            <i class="bi bi-pencil"></i>
          <% end %>
          <%= link_to book, data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: "btn btn-outline-danger" do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<h1> New Book </h1>

<%= render "form", book: @book, authors: @authors, author: @book.author %>

app/views/books/show.html.erb
<div class="container">
<h1> <%= @book.title%> </h1>
<p> <strong>Year:</strong> <%= @book.year %> </p>
<p> <strong>Price:</strong> <%= @book.price %> </p>
<p> <strong>Author:</strong> <%= link_to @book.author.name, @book.author %> </p>
<p> <strong>Publish Date:</strong> <%= @book.publish_date %> </p>
<div class="actions">
  <%= link_to books_path, class: "btn btn-primary" do%>
    <i class="bi bi-arrow-90deg-left"></i> Back
  <% end %>
  <%= link_to edit_book_path(@book), class: "btn btn-warning" do%>
    <i class="bi bi-pencil"></i> Edit
  <% end %>
</div>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BooksApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/books">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/authors">Author</a>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>